version: '3.8'

services:
  clientDB:
    image: postgres:13
    container_name: client_db_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: clientDB
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:  # Define el volumen para almacenar los datos de PostgreSQL
