version: '3.8'

services:
  clientDB:
    image: postgres:13
    container_name: client_db_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: clientDB
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - clientdb_data:/var/lib/postgresql/data

  productDB:
    image: postgres:13
    container_name: product_db_container
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: productDB
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - productdb_data:/var/lib/postgresql/data

volumes:
  clientdb_data:
  productdb_data:
