version: '3.8'

services:
  clientDB:
    image: postgres:13
    container_name: client_db_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: clientDB
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - clientdb_data:/var/lib/postgresql/data

  productDB:
    image: postgres:13
    container_name: product_db_container
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: productDB
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - productdb_data:/var/lib/postgresql/data

  kafka:
    image: confluentinc/cp-kafka:7.3.2
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_BROKER_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_LISTENERS: 'PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
    volumes:
      - ./scripts/workaround.sh:/tmp/workaround.sh
    command: "bash -c 'chmod +x /tmp/workaround.sh && /tmp/workaround.sh && /etc/confluent/docker/run'"
    healthcheck:
      test: ["CMD", "nc", "-z", "localhost", "9092"]
      interval: 5s
      retries: 10

volumes:
  clientdb_data:
  productdb_data: