spring:
  application:
    name: gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      locator:
        enabled: true
      routes:
        - id: client-service-route
          uri: lb://CLIENT-SERVICE
          predicates:
            - Path=/clients/**
        - id: product-service-route
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/accounts/**,/movements/**

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}