spring:
  application:
    name: product-service
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://${HOST_PRODUCT}:${PORT_PRODUCT}/${DATABASE_PRODUCT}
    username: ${USERNAME_PRODUCT}
    password: ${PASSWORD_PRODUCT}
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
    hikari:
      pool-name: SpringHikariCP
      auto-commit: false
      connection-timeout: 300
      maximum-pool-size: 10
  kafka:
    topic:
      name: reports
    bootstrap-servers: localhost:9092
    consumer:
      group-id: group-product
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer

server:
  port: 8082
