-- Crear tabla t_persons si no existe
CREATE TABLE IF NOT EXISTS t_persons (
    per_id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY (MINVALUE 0 NO MAXVALUE START 0 NO CYCLE),
    per_age int4 NOT NULL,
    per_address varchar(255) NOT NULL,
    genre varchar(255) NULL,
    per_dni varchar(255) NOT NULL,
    per_name varchar(255) NOT NULL,
    per_phone varchar(255) NOT NULL,
    CONSTRAINT t_persons_genre_check CHECK ((genre::text = ANY (ARRAY['MALE', 'FEMALE']::text[]))),
    CONSTRAINT t_persons_pkey PRIMARY KEY (per_id),
    CONSTRAINT ukfh2ugalpie9vwaghw34br4f7l UNIQUE (per_dni)
);

-- Crear tabla t_clients si no existe
CREATE TABLE IF NOT EXISTS t_clients (
    cli_password varchar(255) NOT NULL,
    cli_status int4 NULL,
    per_id int4 NOT NULL,
    CONSTRAINT t_clients_pkey PRIMARY KEY (per_id),
    CONSTRAINT fkf2gqdav15y23k29hnrfxbu7al FOREIGN KEY (per_id) REFERENCES t_persons(per_id)
);
